---
- name: Setup Laravel Application Server
  hosts: laravel
  become: true

  vars:
    php_version: "8.3"
    project_dir: "/var/www/sayapatri-backend"
    repo_url: "https://github.com/Ek-Ra-Sunya/sayapatri-backend.git"
    github_user: "{{ lookup('env','GITHUB_USER') }}"
    github_token: "{{ lookup('env','GITHUB_TOKEN') }}"
    nginx_conf: "/etc/nginx/sites-available/laravel"
    db_name: "homestead"
    db_user: "homestead"
    db_password: "secret"

  tasks:
    # -----------------
    # System Updates
    # -----------------
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade security updates only
      apt:
        upgrade: safe

    - name: Install base packages
      apt:
        name:
          - software-properties-common
          - ca-certificates
          - lsb-release
          - apt-transport-https
          - unzip
          - git
        state: present

    # -----------------
    # PHP Setup
    # -----------------
    - name: Add ondrej/php PPA
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Install PHP and extensions
      apt:
        name:
          - "php{{ php_version }}"
          - "php{{ php_version }}-cli"
          - "php{{ php_version }}-common"
          - "php{{ php_version }}-mysql"
          - "php{{ php_version }}-xml"
          - "php{{ php_version }}-mbstring"
          - "php{{ php_version }}-bcmath"
          - "php{{ php_version }}-curl"
          - "php{{ php_version }}-gd"
          - "php{{ php_version }}-zip"
          - "php{{ php_version }}-fpm"
        state: present
        update_cache: yes

    # -----------------
    # Composer Setup
    # -----------------
    - name: Download composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Install composer globally
      command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    # -----------------
    # Clone Laravel Repo
    # -----------------
    - name: Ensure /var/www exists
      file:
        path: /var/www
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Mark project directory as safe for git
      command: git config --global --add safe.directory /var/www/sayapatri-backend
      become: yes
      become_user: www-data

    - name: Clone Laravel project
      git:
        repo: "https://{{ github_user }}:{{ github_token }}@{{ repo_url | regex_replace('^https://', '') }}"
        dest: "{{ project_dir }}"
        version: main

    - name: Create storage subdirectories
      file:
        path: "{{ project_dir }}/storage/framework/{{ item }}"
        state: directory
        mode: '0775'
        owner: www-data
        group: www-data
      loop:
        - cache
        - data
        - sessions
        - views

    # -----------------
    # Ownership & Permissions
    # -----------------
    - name: Ensure correct ownership for Laravel project
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set directory permissions to 775
      command: find {{ project_dir }} -type d -exec chmod 775 {} \;

    - name: Set file permissions to 664
      command: find {{ project_dir }} -type f -exec chmod 664 {} \;

    # -----------------
    # Laravel Setup
    # -----------------
    - name: Install PHP dependencies with Composer
      command: composer install --no-dev --optimize-autoloader
      args:
        chdir: "{{ project_dir }}"
      become_user: www-data

    - name: Ensure .env file exists
      copy:
        src: "{{ project_dir }}/.env.example"
        dest: "{{ project_dir }}/.env"
        remote_src: yes
        force: no

    - name: Ensure .env is writable by www-data
      file:
        path: "{{ project_dir }}/.env"
        owner: www-data
        group: www-data
        mode: '0664'

    - name: Generate Laravel APP_KEY
      command: php artisan key:generate
      args:
        chdir: "{{ project_dir }}"
      become_user: www-data

    # -----------------
    # Database Setup
    # -----------------
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL is running and enabled
      service:
        name: mysql
        state: started
        enabled: true

    - name: Install python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install PyMySQL (needed for Ansible MySQL modules)
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Ensure MySQL user exists
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: localhost
        priv: "*.*:ALL"
        state: present
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Ensure database is created
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: localhost


    - name: Run Laravel migrations
      command: php artisan migrate --force
      args:
        chdir: "{{ project_dir }}"
      become_user: www-data

    - name: Run Laravel seeders
      command: php artisan db:seed --force
      args:
        chdir: "{{ project_dir }}"
      become_user: www-data

    # -----------------
    # Nginx Setup
    # -----------------
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Configure nginx for Laravel
      copy:
        dest: "{{ nginx_conf }}"
        content: |
          server {
              listen 80;
              server_name _;
              root {{ project_dir }}/public;

              index index.php index.html index.htm;

              location / {
                  try_files $uri $uri/ /index.php?$query_string;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php{{ php_version }}-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }

              location ~ /\.ht {
                  deny all;
              }
          }
      notify: restart nginx

    - name: Enable nginx site
      file:
        src: "{{ nginx_conf }}"
        dest: /etc/nginx/sites-enabled/laravel
        state: link
        force: true

    # -----------------
    # Final Permissions Fix
    # -----------------
    - name: Ensure storage and cache writable
      file:
        path: "{{ project_dir }}/{{ item }}"
        mode: '0775'
        recurse: yes
        owner: www-data
        group: www-data
      loop:
        - storage
        - bootstrap/cache

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php-fpm
      service:
        name: "php{{ php_version }}-fpm"
        state: restarted
        enabled: true
